---
openapi: 3.0.0
info:
  title: Diet Tracker Audit API
  description: This API receives nutritional information from a diet tracker
  contact:
    email: sjung97@my.bcit.ca
  version: 1.0.0
servers:
- url: /
tags:
- name: devices
  description: Operations available to diet tracker devices
paths:
  /calories:
    get:
      summary: gets meal calories from history
      operationId: app.get_meal_calories
      description: gets meal calories from event store
      parameters:
        - name: index
          in: query
          description: Gets meal calories at the index from the event store
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: successfully returned meal calorie event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Calories'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /weight:
    get:
      summary: gets user weight from history
      operationId: app.get_user_weight
      description: gets user weight from the event store
      parameters:
        - name: index
          in: query
          description: Gets user weight at the index from the event store
          schema:
            type: integer
            example: 100
      responses:
        '200':
          description: successfully returned user weight event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Calories'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  schemas:
    Calories:
      required:
      - calorie_count
      - meal_name
      - meal_number
      - timestamp
      - user_id
      type: object
      properties:
        user_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        meal_name:
          type: string
          example: Rice Bowl
        meal_number:
          type: integer
          example: 1
        calorie_count:
          type: integer
          example: 120
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
    Weight:
      required:
      - timestamp
      - user_id
      - weight_kg
      - weight_lbs
      type: object
      properties:
        user_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        weight_kg:
          type: integer
          example: 60
        weight_lbs:
          type: integer
          example: 132
        timestamp:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
